### PR TITLE
login and register boilerplate 

### PR DESCRIPTION
**Pull request by ezioguga**

### CODE REVIEW

**Comment by ezioguga** [comment]
I have attached the sample login and register boilerplate.

**Comment by Safnaj** [comment]
@ezioguga Thanks for interested to contribute to this project. Actually boiler plate doesn't required any feature developed. 
There has to be a proper architecture/structure only. 

Correct me if i am wrong @Shehanka @dilum1995

**Comment by Shehanka** [comment]
> @ezioguga Thanks for interested to contribute to this project. Actually boiler plate doesn't required any feature developed.
> There has to be a proper architecture/structure only.
> 
> Correct me if i am wrong @Shehanka @dilum1995

@Safnaj You're correct. We need proper structure

**Review by Shehanka — CHANGES_REQUESTED** [review]
Implement with a proper structure

**Pull request closed without merging**
